
name: Snapshot

on:
  schedule:
    - cron:  '0 3 * * *'
  push:
    branches: [ master ]

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
      -   name: Setup JDK 11
          uses: actions/setup-java@v1
          with:
            java-version: 11

      -   name: Check out sources...
          uses: actions/checkout@v2

      -   name: Build with Gradle
          run: ./gradlew distZip distTar

      - name: Rename .ZIP
        run: mv build/distributions/JDFEditor-development.zip build/distributions/JDFEditor-SNAPSHOT-${{ github.run_number }}.zip

      - name: Rename .TAR
        run: mv build/distributions/JDFEditor-development.tar build/distributions/JDFEditor-SNAPSHOT-${{ github.run_number }}.tar

      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: build/distributions/Alces-SNAPSHOT-*.*

  macos-build:
    runs-on: macos-latest
    steps:
      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Check out sources...
        uses: actions/checkout@v2

      - name: Build with Gradle
        run: ./gradlew createDmg

      - name: Rename .DMG
        run: mv build/distributions/JDFEditor-development.dmg build/distributions/JDFEditor-SNAPSHOT-${{ github.run_number }}.dmg

      - name: Upload Binaries
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: build/distributions/JDFEditor-SNAPSHOT-*.*

  windows-build:
    runs-on: windows-latest
    steps:
      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Check out sources...
        uses: actions/checkout@v2

      - name: Build with Gradle
        run: ./gradlew createExe

      - name: Rename binaries
        run: mv build/launch4j/JDFEditor-development.exe build/launch4j/JDFEditor-SNAPSHOT-${{ github.run_number }}.exe

      - name: Debug
        run: ls -l build/launch4j

      - name: Upload EXE
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: build/launch4j/JDFEditor-SNAPSHOT-*.exe

  publish-snapshot:
    needs:
      - linux-build
      - macos-build
      - windows-build
    runs-on: ubuntu-latest
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v2
        with:
          name: binaries
          path: binaries
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: binaries
      - name: Confluence Upload
        uses: cip4/action-confluence-upload@master
        with:
          url: 'https://confluence.cip4.org'
          username: ${{ secrets.CONFLUENCE_USER }}
          password: ${{ secrets.CONFLUENCE_PASSWORD }}
          contentId: 5309046
          label: 'jdfeditor-snapshot,snapshot'
          filePattern: 'binaries/**/JDFEditor-SNAPSHOT-*.*'
