
name: Snapshot

on:
  schedule:
    - cron:  '0 3 * * *'
  push:
    branches: [ master ]

jobs:
  linux-build:
    runs-on: macos-latest
    steps:
      -   name: Setup JDK 11
          uses: actions/setup-java@v1
          with:
            java-version: 11

      -   name: Check out sources...
          uses: actions/checkout@v2

      -   name: Build with Gradle
          run: ./gradlew distZip distTar

      -   name: ZIP Package
          uses: actions/upload-artifact@v1
          with:
            name: zip package
            path: build/distributions/JDFEditor-development.zip

      -   name: TAR Package
          uses: actions/upload-artifact@v1
          with:
            name: tar package
            path: build/distributions/JDFEditor-development.tar

  macos-build:
    runs-on: macos-latest
    steps:
      - name: Setup JDK 1
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Check out sources...
        uses: actions/checkout@v2

      - name: Build with Gradle
        run: ./gradlew createDmg

      - name: Upload MacOS App
        uses: actions/upload-artifact@v1
        with:
          name: macos app file
          path: build/distributions/JDFEditor-development.dmg

      - name: Upload JAR
        uses: actions/upload-artifact@v1
        with:
          name: jar file
          path: build/libs/JDFEditor-development.jar

  windows-build:
    runs-on: windows-latest
    steps:
      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Check out sources...
        uses: actions/checkout@v2

      - name: Build with Gradle
        run: ./gradlew createExe

      - name: Debug
        run: ls -l build/launch4j

      - name: Upload EXE
        uses: actions/upload-artifact@v1
        with:
          name: exe file
          path: build/launch4j/JDFEditor-development.exe
